#define IDD_CUVETTE_DIALOG              102
#define IDD_MAIN_TAB1                   105
#define IDR_MAINFRAME                   128
#define IDR_MAINMENU                    130
#define IDD_IMPORT_DIALOG               131
#define IDD_MAIN_TAB2                   132
#define IDD_VIEW_DIALOG                 134
#define IDD_VIEW_PROPERTIES_DIALOG      136
#define IDR_MENU1                       139
#define IDD_DIALOG_SET_GROUP_NAME       140
#define IDD_ISOTOPE_DIALOG              143
#define IDD_MAIN_TAB3                   144
#define IDD_DIALOG_ABOUT                146
#define IDB_BITMAP_LOGO                 148
#define IDD_DIALOG_ADDDORB              150
#define IDD_DIALOG_DISPLAY_SIM_DATA     152
#define IDD_IMPORT_ENSEMBLE             154
#define IDD_DIALOG_EDITREFERENCE        156
#define IDD_DIALOG_STATERROR            158
#define IDD_DIALOG_GVALUE               162
#define IDD_DIALOG_UPDATES              164
#define IDC_GRAPH_PANEL                 1003
#define IDC_CHECK_GRAPH1                1004
#define IDC_CHECK_GRAPH2                1005
#define IDC_CHECK_IMPORT_REFSPC         1006
#define IDC_COMBO_REFERENCE             1007
#define IDC_TEXTFIELD_IMPORT_REFSPC     1008
#define IDC_CHECK_IMPORT_MOL            1009
#define IDC_CHECK_IMPORT_MOLREF         1010
#define IDC_COMBO_IMPORT_MOLREF         1011
#define IDC_CHECK_IMPORT_NMR            1012
#define IDC_CHECK_IMPORT_HFC            1013
#define IDC_CHECK_IMPORT_CASSCF         1014
#define IDC_COMBO_IMPORT_CASSCF         1015
#define IDC_CHECK_IMPORT_FC             1016
#define IDC_TEXTFIELD_IMPORT_FC         1017
#define IDC_TEXTFIELD_IMPORT_HFC        1018
#define IDC_TEXTFIELD_IMPORT_SHIFT      1019
#define IDC_MAINTAB                     1021
#define IDC_LIST                        1022
#define IDC_STATIC_VIEWSMALL            1023
#define IDC_STATIC_VIEWLARGE            1024
#define IDOK2                           1027
#define IDRESET                         1028
#define IDC_COMBO_SPHERE_NAME           1029
#define IDC_MFCCOLORBUTTON1             1031
#define IDC_MFCCOLORBUTTON2             1032
#define IDC_COMBO_CNN_NAME_A            1033
#define IDC_COMBO_CNN_NAME_B            1034
#define IDC_COMBO_CNN_THRESHOLD         1035
#define IDC_COMBO_SPHERE_RADIUS         1036
#define IDC_COMBO_CNN_THRESHOLD2        1037
#define IDC_LIST1                       1038
#define IDC_EDIT_GROUPNAME              1039
#define IDC_LIST_BODY_EDITDORB          1039
#define IDC_COMBO_NUCLEUS               1041
#define IDC_EDIT_TEMPERATURE            1042
#define IDC_EDIT_MAGFIELD               1043
#define IDC_COMBO_SHIELDING_DATA        1044
#define IDC_COMBO_FC_DATA               1045
#define IDC_COMBO_HFC_DATA              1046
#define IDC_COMBO_SIM_FC                1047
#define IDC_COMBO_SIM_PC                1048
#define IDC_COMBO_SIM_SUSCEPTIBILITY    1049
#define IDC_EDIT_PDA_POSX               1050
#define IDC_EDIT_PDA_POSY               1051
#define IDC_EDIT_PDA_POSZ               1052
#define IDC_COMBO_SIM_CURVETYPE         1053
#define IDC_BUTTON_SIMULATE             1054
#define IDC_COMBO_RELAXATION_CONTACT    1055
#define IDC_COMBO_RELAXATION_DIPOLAR    1056
#define IDC_COMBO_RELAXATION_CURIE      1057
#define IDC_EDIT_INDIVIDUAL_SUS_XX      1058
#define IDC_EDIT_INDIVIDUAL_SUS_XY      1059
#define IDC_EDIT_INDIVIDUAL_SUS_XZ      1060
#define IDC_EDIT_INDIVIDUAL_SUS_YX      1061
#define IDC_EDIT_INDIVIDUAL_SUS_YY      1062
#define IDC_EDIT_INDIVIDUAL_SUS_YZ      1063
#define IDC_EDIT_INDIVIDUAL_SUS_ZX      1064
#define IDC_EDIT_INDIVIDUAL_SUS_ZY      1065
#define IDC_EDIT_INDIVIDUAL_SUS_ZZ      1066
#define IDC_EDIT_INDIVIDUAL_SUS_ISO     1067
#define IDC_EDIT_INDIVIDUAL_SUS_ANISO   1068
#define IDC_STATIC_CHIISO               1069
#define IDC_STATIC_CHIDIP               1070
#define IDC_EDIT_COMP_SUS_XX            1071
#define IDC_STATIC_CHIISO2              1072
#define IDC_STATIC_CHIDIP2              1073
#define IDC_EDIT_COMP_SUS_XY            1074
#define IDC_EDIT_COMP_SUS_XZ            1075
#define IDC_EDIT_COMP_SUS_YX            1076
#define IDC_EDIT_COMP_SUS_YY            1077
#define IDC_EDIT_COMP_SUS_YZ            1078
#define IDC_EDIT_COMP_SUS_ZX            1079
#define IDC_EDIT_COMP_SUS_ZY            1080
#define IDC_EDIT_COMP_SUS_ZZ            1081
#define IDC_EDIT_COMP_SUS_ISO           1082
#define IDC_EDIT_COMP_SUS_ANISO         1083
#define IDC_COMBO_COMPCHI_TEMP          1084
#define IDC_EDIT_FITTED_SUSXX           1085
#define IDC_EDIT_FITTED_SUSXY           1086
#define IDC_EDIT_FITTED_SUSXZ           1087
#define IDC_EDIT_FITTED_SUSYX           1088
#define IDC_EDIT_FITTED_SUSYY           1089
#define IDC_EDIT_FITTED_SUSYZ           1090
#define IDC_EDIT_FITTED_SUSZX           1091
#define IDC_EDIT_FITTED_SUSZY           1092
#define IDC_EDIT_FITTED_SUSZZ           1093
#define IDC_EDIT_FITTED_SUS_ISO         1094
#define IDC_EDIT_FITTED_SUS_ANISO       1095
#define IDC_STATIC_CHIISO3              1096
#define IDC_STATIC_CHIDIP3              1097
#define IDC_EDIT_FITTED_ACTXX           1098
#define IDC_BUTTON_FITTING              1099
#define IDC_BUTTON_SYM_RESET            1100
#define IDC_EDIT_FITTED_ACTXY           1101
#define IDC_COMBO_ISOTOPE_SELECTION     1101
#define IDC_EDIT_FITTED_ACTXZ           1102
#define IDC_EDIT_FITTED_ACTYX           1103
#define IDC_EDIT_FITTED_ACTYY           1104
#define IDC_EDIT_FITTED_ACTYZ           1105
#define IDC_EDIT_FITTED_ACTZX           1106
#define IDC_EDIT_FITTED_ACTZY           1107
#define IDC_EDIT_FITTED_ACTZZ           1108
#define IDC_BUTTON_FITTOIND             1109
#define IDC_BUTTON_COMPTOIND            1110
#define IDC_CHECK_FIT_REL               1111
#define IDC_EDIT_TRUSTRADIUS            1112
#define IDC_SLIDER_RELAX_T1E            1113
#define IDC_SLIDER_RELAX_T2E            1114
#define IDC_SLIDER_RELAX_TM             1115
#define IDC_SLIDER_RELAX_TR             1116
#define IDC_EDIT_T1E_VAL                1117
#define IDC_EDIT_T2E_VAL                1118
#define IDC_EDIT_TM_VAL                 1119
#define IDC_EDIT_TR_VAL                 1120
#define IDC_EDIT_T1E_EXPONENT           1121
#define IDC_EDIT_T2E_EXPONENT           1122
#define IDC_EDIT_TM_EXPONENT            1123
#define IDC_EDIT_TR_EXPONENT            1124
#define IDC_BUTTON_EXPSPC_REMOVE        1125
#define IDC_BUTTON_EXPSPC_HIDE          1126
#define IDC_COMBO_REL_SOLVENT           1127
#define IDC_EDIT_SPHERE_RADIUS          1128
#define IDC_BUTTON_GET_SPHERICAL_VOL    1129
#define IDC_BUTTON_GET_ELLIPSOID_VOL    1130
#define IDC_STATIC_LOGOPICTURE          1131
#define IDC_COMBO_SHOWBY                1133
#define IDC_BUTTON_ADDNEWDORB           1134
#define IDC_EDIT_RENAME_DORB            1135
#define IDC_COMBO_SELECT_DORB           1136
#define IDC_COMBO_APPLYREF              1137
#define IDC_LIST_HEAD_EDITDORB          1138
#define IDC_COMBO_ADDANISO              1139
#define IDC_STATIC_DORBSELECT_TEXT      1141
#define IDC_STATIC_ADAPTSIGMA           1142
#define IDC_LIST_SIMDATA_HEAD           1143
#define IDC_LIST_SIMDATA_BODY           1144
#define IDC_LISTBOX_INFO                1144
#define IDCREATE                        1145
#define IDC_EDIT_ENSEMBLE_TEMPERATURE   1146
#define IDC_BUTTON_REMOVE_DIAMAG        1147
#define IDC_BUTTON_REMOVE_FERMI         1148
#define IDC_STATIC_CUBIC_ANGSTROM       1148
#define IDC_BUTTON_REMOVE_FERMI2        1149
#define IDC_BUTTON_REMOVE_HFC           1149
#define IDC_LIST_ERROR_INFORMATION      1149
#define IDC_EDIT_ERRORCHIXX             1150
#define IDC_EDIT_ERRORCHIXY             1151
#define IDC_EDIT_ERRORCHIXZ             1152
#define IDC_EDIT_ERRORCHIYX             1153
#define IDC_EDIT_ERRORCHIYY             1154
#define IDC_EDIT_ERRORCHIYZ             1155
#define IDC_EDIT_ERRORCHIZX             1156
#define IDC_EDIT_ERRORCHIZY             1157
#define IDC_EDIT_ERRORCHIZZ             1158
#define IDC_EDIT_ERRORCHI_ISO           1159
#define IDC_EDIT_ERRORCHI_ANISO         1160
#define IDC_STATIC_CHI2RED              1161
#define IDC_STATIC_R2                   1162
#define IDC_STATIC_R2ADJ                1163
#define IDC_STATIC_ERRORCHIISO_TEXT     1164
#define IDC_STATIC_ERRORCHIANISO_TEXT   1165
#define IDC_STATIC_CHIQUADRED_TEXT      1166
#define IDC_STATIC_R2_TEXT              1167
#define IDC_STATIC_R2ADJ_TEXT           1168
#define IDC_LIST_SIGNALERROR            1169
#define IDC_EDIT_G_XX                   1170
#define IDC_EDIT_G_XY                   1171
#define IDC_EDIT_G_XZ                   1172
#define IDC_EDIT_G_YX                   1173
#define IDC_EDIT_G_YY                   1174
#define IDC_EDIT_G_YZ                   1175
#define IDC_EDIT_G_ZX                   1176
#define IDC_EDIT_G_ZY                   1177
#define IDC_EDIT_G_ZZ                   1178
#define IDC_BUTTON_G_RESET              1179
#define IDC_EDIT_ADDREFERENCE           1181
#define IDC_COMBO_ADDREFELEMENTS        1182
#define IDC_STATIC_UPDATE_INFO_TEXT     1183
#define ID_FILE                         32771
#define ID_FILE_IMPORT                  32772
#define ID_MENU0_ADDSELECTEDASGROUP     32773
#define ID_MENU0_ADDSELECTEDASINDIVIDUALS 32774
#define ID_MENU0_VIEWPROPERTIES         32775
#define ID_MENU0_DESELECTALL            32776
#define ID_MENU0_DESELECT_ALL           32777
#define ID_EDIT_EDITREFERENCESHIFTS     32778
#define ID_FILE_IMPORT32779             32779
#define ID_FILE_EXPORT                  32780
#define ID_FILE_EXIT                    32781
#define ID_EDIT_EDITORBITALSHIFTS       32782
#define ID_EDIT_DESELECTDATA            32783
#define ID_EDIT_DELETESELECTEDDATA      32784
#define ID_VERSION_ABOUT                32785
#define ID_EDIT_DISPLAYSIMULATIONDATA   32786
#define ID_EDIT_CREATEENSEMBLE          32787
#define ID_TOOLS_CREATEEMPTYHFCDATA     32788
#define ID_TOOLS_DISPLAYFITSTATISTICS   32789
#define ID_TOOLS_EDITG                  32790
#define ID_TOOLS_EDITGTENSOR            32791
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        166
#define _APS_NEXT_COMMAND_VALUE         32792
#define _APS_NEXT_CONTROL_VALUE         1184
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
